### ISSUE TITLE
Unable to implemenrt sorttable.js on dynamically added table data

### ISSUE THREAD

**Issue by pique-b** [stuartlangridge/sorttable#38]
I have used the excellent library **_sorttable.js_**. So far I have used them on static tables with prefilled data.

In an application I am now trying to use it on a table which is **a.** created based on data received as ajax callback, **b.** the IDs are created once the table is created, and then, **c.** the table is populated with data from the backend.

I am trying to use the similar methodology as I have employed on my `static` tables but am running into errors.

1. If I use `sortable` in `<table>` tag, the following error is generated:

```
	Uncaught TypeError: node.getAttribute is not a function
	at Object.getInnerText (sorttable.js:211:14)
	at Object.getInnerText (sorttable.js:236:36)
	at Object.guessType (sorttable.js:170:24)
	at Object.makeSortable (sorttable.js:87:56)
	at sorttable.js:36:19
	at Array.forEach (sorttable.js:453:10)
	at forEach (sorttable.js:492:11)
	at HTMLDocument.init (sorttable.js:34:5)

```

2. As per a suggestion in response to one of the queries here (on Github), I have tried to kind of defer calling the `sorttable.js` before the data is populated, like so:

```
	var newListTable = document.getElementById('listTable');
	sorttable.makeSortable(newListTable);
```

And in this instant case too, the following error is generated:

```
	Uncaught TypeError: node.getAttribute is not a function
	at Object.getInnerText (sorttable.js:211:14)
	at Object.getInnerText (sorttable.js:236:36)
	at Object.guessType (sorttable.js:170:24)
	at Object.makeSortable (sorttable.js:87:56)

```

I am currently using the latest sorttable.js script file available on github.

Is there a way that I may have the sort feature implemented in this case, where the table data is populated through Ajax?

I am using `jquery-3.4.1.js`
on **Chrome** Version 103.0.5060.134 (Official Build) (x86_64)

Thanks

**Comment by pique-b** [comment]
On a hunch checked the browser error script and found that the old `sorttable.js` script was coming into play! On removing the cookies, the sort functionality worked perfectly.

And it was getting stuck here:

`if (node.nodeType == 1 && node.getAttribute("sorttable_customkey") !== null) {`

with the original code reading: `if (node.getAttribute("sorttable_customkey") !== null) {`

This issue was discussed [here](https://github.com/stuartlangridge/sorttable/issues/6#issue-92649861)

Closing the issue.
